import {
  Activity,
  AlertCircle,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Binary,
  BookOpen,
  Boxes,
  Braces,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Code2,
  Command,
  Compass,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Flame,
  FolderGit2,
  Gauge,
  GitBranch,
  GitFork,
  Github,
  Globe,
  GraduationCap,
  Heart,
  Home,
  KeyRound,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Linkedin,
  ListChecks,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  Milestone,
  Moon,
  Network,
  Phone,
  Puzzle,
  Quote,
  Rocket,
  School,
  ScrollText,
  Search,
  Send,
  Server,
  Shield,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  TestTube2,
  TrendingUp,
  Trophy,
  Users,
  Workflow,
  Wrench,
  X,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * Central icon registry.
 *
 * Content files under `src/data` reference icons by *name* (a plain string)
 * rather than importing components directly. That keeps the content layer free
 * of React imports — editing your portfolio never means touching JSX — while
 * `IconName` below still gives you compile-time safety and editor
 * autocomplete on every name you type.
 */
export const ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  award: Award,
  binary: Binary,
  'book-open': BookOpen,
  boxes: Boxes,
  braces: Braces,
  briefcase: Briefcase,
  bug: Bug,
  building: Building2,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  code: Code2,
  command: Command,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-text': FileText,
  flame: Flame,
  'folder-git': FolderGit2,
  gauge: Gauge,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  github: Github,
  globe: Globe,
  graduation: GraduationCap,
  heart: Heart,
  home: Home,
  key: KeyRound,
  layers: Layers,
  dashboard: LayoutDashboard,
  lightbulb: Lightbulb,
  linkedin: Linkedin,
  'list-checks': ListChecks,
  loader: Loader2,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  milestone: Milestone,
  moon: Moon,
  network: Network,
  phone: Phone,
  puzzle: Puzzle,
  quote: Quote,
  rocket: Rocket,
  school: School,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  server: Server,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  terminal: Terminal,
  'test-tube': TestTube2,
  'trending-up': TrendingUp,
  trophy: Trophy,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export const getIcon = (name: IconName): LucideIcon => ICONS[name]
